DROP TABLE EMPINFO;
DROP TABLE CUSTINFO;
DROP TABLE SUPPLIERINFO;
DROP TABLE PRODUCTINFO;
DROP TABLE TRANSACTIONDETAILS;
DROP TABLE SUPPLIER;
DROP TABLE PRODUCT;
DROP TABLE SERVICE;
DROP TABLE TRANSACTION;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;

DROP SEQUENCE EmpID_Seq;
DROP SEQUENCE CustID_Seq;
DROP SEQUENCE ProdID_Seq;
DROP SEQUENCE ServID_Seq;
DROP SEQUENCE SuppID_Seq;
DROP SEQUENCE TransID_Seq;
DROP SEQUENCE EinfoID_Seq;
DROP SEQUENCE CinfoID_Seq;
DROP SEQUENCE SinfoID_Seq;
DROP SEQUENCE PinfoID_Seq;
DROP SEQUENCE TinfoID_Seq;

